"""add excerpt to announcements

Revision ID: 6791f194fbba
Revises: 8f202abb5d45
Create Date: 2026-04-15 17:54:06.973212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6791f194fbba'
down_revision = '8f202abb5d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excerpt', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_column('excerpt')

    # ### end Alembic commands ###
